### ISSUE TITLE
Week3 , Description about experiments

### ISSUE THREAD

**Issue by appuCoding** [soumyaramesh/web-dev#1]
You have done good job this week . Professor is expecting a paragraph about the experiments. 
You can write why are you doing this experiment , what will be the use of the experiment in real industry or in your future project.

**Comment by soumyaramesh** [comment]
Hi Sneha,

This week, I have elaborated a little more about my experiment. I have added a section called Description which describes the experiment in detail and the code snippet. In my blog posts, I have added what I learnt from the experiment. Please let me know if this is what was expected from my end. Thanks
